version: "3.1"

services:
  scheduler:
    image: ghcr.io/dask/dask:2022.4.0-py3.9
    hostname: scheduler
    ports:
      - "8786:8786"
      - "8787:8787"
    command: ["dask-scheduler"]

  worker:
    image: ghcr.io/dask/dask:2022.4.0-py3.9
    command: ["dask-worker", "tcp://scheduler:8786"]
    # For Docker swarm you can specify multiple workers, this is ignored by `docker-compose up`
    deploy:
      replicas: 1
    environment:
      - EXTRA_PIP_PACKAGES=dagster_dask dagster_docker dagster_postgres requests
      - POSTGRESQL_URI=$POSTGRESQL_URI
    volumes:
      - "./pipelines:/app/codes"

