version: "3.1"

services:
  grpc:
    image: 0x0400/dagster
    build: .
    command: dagster api grpc -d /app/codes/ -m dask_demo --host 0.0.0.0 --port 4266
    #command: dagster api grpc -f /home/ubuntu/dask-test/docker_demo.py --host 0.0.0.0 --port 4266
    working_dir: /app
    environment:
      - DAGSTER_HOME=/app/runtime
      - DAGSTER_CURRENT_IMAGE=0x0400/dagster
      - POSTGRESQL_URI=$POSTGRESQL_URI
    volumes:
      - "./pipelines/dask_demo.py:/app/codes/dask_demo.py"
      - "./dagster.yaml:/app/runtime/dagster.yaml"
      - "/var/run/docker.sock:/var/run/docker.sock"
  grpc1:
    image: 0x0400/dagster
    build: .
    command: dagster api grpc -d /app/codes/ -m docker_demo --host 0.0.0.0 --port 4266
    working_dir: /app
    environment:
      - DAGSTER_HOME=/app/runtime
      - DAGSTER_CURRENT_IMAGE=0x0400/dagster-code
      - POSTGRESQL_URI=$POSTGRESQL_URI
    volumes:
      - "./pipelines/docker_demo.py:/app/codes/docker_demo.py"
      - "./dagster.yaml:/app/runtime/dagster.yaml"
      - "/var/run/docker.sock:/var/run/docker.sock"
  grpc2:
    image: 0x0400/dagster
    build: .
    command: dagster api grpc -d /app/codes/ -m multi_jobs --host 0.0.0.0 --port 4266
    working_dir: /app
    environment:
      - DAGSTER_HOME=/app/runtime
      - DAGSTER_CURRENT_IMAGE=0x0400/dagster
      - POSTGRESQL_URI=$POSTGRESQL_URI
    volumes:
      - "./pipelines/multi_jobs.py:/app/codes/multi_jobs.py"
      - "./dagster.yaml:/app/runtime/dagster.yaml"
      - "/var/run/docker.sock:/var/run/docker.sock"

  web:
    image: 0x0400/dagster
    build: .
    command: dagit -h 0.0.0.0 -w /app/workspace.yaml
    #command: dagster api grpc -f /home/ubuntu/dask-test/docker_demo.py --host 0.0.0.0 --port 4266
    ## multi jobs
    #command: dagit -h 0.0.0.0 -p 3001 -w pipelines.yaml
    environment:
      - DAGSTER_HOME=/app/runtime
      #- DAGSTER_CURRENT_IMAGE=0x0400/dagster
      - POSTGRESQL_URI=$POSTGRESQL_URI
    working_dir: /app
    volumes:
      - "/home/ubuntu/dask-test/workspace.yaml:/app/workspace.yaml"
      - "./dagster.yaml:/app/runtime/dagster.yaml"
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "3000:3000"

  code:
    image: 0x0400/dagster-code
    build:
      context: .
      dockerfile: Dockerfile.code

